In [1]:
import pandas as pd

In [2]:
fh = "src/files/BPLPeriodicals/BPL-Periodicals-not-vendor.txt"

In [3]:
df = pd.read_csv(fh, delimiter="@", names=["bibNo", "title", "OPACdisplay", "vendor", "locationCheckin", "updatedCheckin", "locationItem", "updatedItem"])

In [4]:
df.shape[0]

553

In [5]:
df.head(3)

,bibNo,title,OPACdisplay,vendor,locationCheckin,updatedCheckin,locationItem,updatedItem
0,RECORD #(Bibliographic),TITLE,OPAC DISPLAY,VENDOR,LOCATION,UPDATED,LOCATION,CREATED
1,b100031857,American craft.,-,wtcox^n,50apd^18adk,01-14-2019^03-03-2017,NaN,- -
2,b100033416,The Accountants' directory and who's who.,-,n,23ans,03-03-2017,NaN,- -

In [32]:
central_df = df[(df["locationCheckin"].str.contains(r"01|02|03|04|11|12|13|14|16|17|18|23|90|91|94|95|98"))|(df["locationItem"].str.contains(r"01|02|03|04|11|12|13|14|16|17|18|23|90|91|94|95|98"))]

In [33]:
central_df.head(2)

,bibNo,title,OPACdisplay,vendor,locationCheckin,updatedCheckin,locationItem,updatedItem
1,b100031857,American craft.,-,wtcox^n,50apd^18adk,01-14-2019^03-03-2017,NaN,- -
2,b100033416,The Accountants' directory and who's who.,-,n,23ans,03-03-2017,NaN,- -

In [34]:
central_df.shape[0]

502

In [35]:
central_df.to_csv("src/files/BPLPeriodicals/BPL-Central-Periodicals-unclear-vendor.csv", index=False)

In [36]:
other_df = df[(df["locationCheckin"].str.contains(r"21|22|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88"))|(df["locationItem"].str.contains(r"21|22|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88"))]

In [37]:
other_df.shape[0]

131

In [39]:
other_df.to_csv("src/files/BPLPeriodicals/BPL-Branches-Periodicals-unclear-vendor.csv", index=False)

In [43]:
only_branches = df[~df["locationCheckin"].str.contains(r"01|02|03|04|11|12|13|14|16|17|18|23|90|91|94|95|98")&(~df["locationCheckin"].str.contains(r"01|02|03|04|11|12|13|14|16|17|18|23|90|91|94|95|98"))]

In [44]:
only_branches.shape[0]

54

In [45]:
only_branches.to_csv("src/files/BPLPeriodicals/BPL-Branches-Periodicals-Branch-Only.csv", index=False)

In [46]:
not_wtcox = df[~df["vendor"].str.contains("wtcox")]

In [47]:
not_wtcox.shape[0]

468

In [48]:
not_wtcox.to_csv("src/files/BPLPeriodicals/BPL-Branches-Periodicals-NOT-WTCOX.csv", index=False)